server:
  address: 0.0.0.0
  port: 8000
  servlet:
    context-path: 
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
#   mvc: #요걸 적용하게 되면 컨트롤러가 리턴할 때, 앞에 붙여주는 경로명과, 뒤에 부텽주는 경로명이 달라지게 된다. 아래가 자동으로 붙어서 전달.
#     view:
#       prefix: /templates/
#       suffix: .mustache
      
  datasource: # 스프링을 데이터 베이스에 연결 할 것인데 드라이버 클래스네임은 아래와 같고
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul # 데이터 베이스의 시간 설정 진행하고
    driver-class-name: org.mariadb.jdbc.Driver
    username: greenux
    password: 1234

    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 58168191787-18d7l9dui07toflfoquinaup8a33gjeu.apps.googleusercontent.com
            client-secret: Ad7tvb8OyMKk8_GSsTD69QIp
            scope:  
            - email
            - profile
          facebook:
            client-id: 482596159728158
            client-secret: af6a5e76c3757177e1d83bdff50dae45
            scope:  
            - email
            - public_profile
          naver:
            client-id: 8KYmBe8FfFbM5SxQhZmy
            client-secret: 74ArR7rEs_
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code #코드를 부여받는 방식, 코드를 통해 엑세스 토큰을 받는당~
            redirect-uri: http://localhost:8000/login/oauth2/code/naver #구글이나 페이스와 다르게 네이버는 유명한 곳이 아니여서, 적어줘야 한당.

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.