server:
  port: 8000
  servlet:
    context-path: 
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc: #요걸 적용하게 되면 컨트롤러가 리턴할 때, 앞에 붙여주는 경로명과, 뒤에 부텽주는 경로명이 달라지게 된다. 아래가 자동으로 붙어서 전달.
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource: # 스프링을 데이터 베이스에 연결 할 것인데 드라이버 클래스네임은 아래와 같고
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul # 데이터 베이스의 시간 설정 진행하고
    driver-class-name: org.mariadb.jdbc.Driver
    username: greenux
    password: qwer1234

    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
